name: reminder
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  android_alarm_manager_plus: ^2.1.0

  cupertino_icons: ^1.0.2

  
  date_time_picker: ^2.1.0
  dio: ^5.0.0
  firebase_auth: ^4.2.7
  firebase_core: ^2.6.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  formz: ^0.4.1
  get: 4.6.5
  get_it: ^7.2.0
  get_storage: ^2.0.3
  intl: ^0.17.0
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  sqflite: ^2.2.3
 
  table_calendar: ^3.0.8
  timezone: ^0.9.1



dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/file/
